MyCRUD/Models/ErrorViewModel.cs
using System;

namespace MyCRUD.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

MyCRUD/Models/Libro.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyCRUD.Models
{
	public class Libro
	{
		[Key]
		public int Id { get; set; }

		[Required(ErrorMessage = "El título es obligatorio")]
		[StringLength(50, ErrorMessage = "El {0} debe ser al menos {2} y maximo {1} caracteres", MinimumLength =3)]
		[Display(Name = "Título")]
		public string Titulo { get; set; }


		[Required(ErrorMessage = "La descripción es obligatoria")]
		[StringLength(255, ErrorMessage = "El {0} debe ser al menos {2} y maximo {1} caracteres", MinimumLength = 3)]
		[Display(Name = "Descipción")]
		public string Descripcion { get; set; }

		[Required(ErrorMessage = "La fecha es obligatoria")]
		[DataType(DataType.Date)]
		[Display(Name = "Fecha Lanzamiento")]
		public DateTime FechaLanzamiento { get; set; }

		[Required(ErrorMessage = "El autor es obligatorio")]
		public string Autor { get; set; }
		[Required(ErrorMessage = "El precio es obligatorio")]
		public int Precio { get; set; }
	}
}

MyCRUD/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyCRUD.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MyCRUD.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

MyCRUD/Controllers/LibrosController.cs
using Microsoft.AspNetCore.Mvc;
using MyCRUD.Data;
using MyCRUD.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyCRUD.Controllers
{
	public class LibrosController : Controller
	{
		#region Miembros
		private readonly ApplicationDbContext _context;
		#endregion

		#region Constructor
		public LibrosController(ApplicationDbContext context)
		{
			_context = context;
		}
		#endregion

		#region Index
		public IActionResult Index()
		{
			IEnumerable<Libro> listaLibros = _context.Libro;
			return View(listaLibros);
		}
		#endregion

		#region Create Formulario para crear un nuevo libro
		public IActionResult Create()
		{

			return View();
		}
		#endregion

		#region Metodo HttpPost para agregar un nuevo libro
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(Libro libro)
		{
			if (ModelState.IsValid)
			{
				_context.Libro.Add(libro);
				_context.SaveChanges();
				TempData["mensaje"] = "El libro se ha guardado correctamente";
				return RedirectToAction("Index");
			}
			return View();
		}
		#endregion

		#region Formulario para editar un libro
		public IActionResult Edit(int? id)
		{
			if(id == null || id.Equals(0))
			{
				return NotFound();
			}

			//Obtener libro 
			var libro = _context.Libro.Find(id);
			if(libro == null)
			{
				return NotFound();
			}
			return View(libro);
		}
		#endregion

		#region Metodo HttpPost para editar un libro
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(Libro libro)
		{
			if (ModelState.IsValid)
			{
				_context.Libro.Update(libro);
				_context.SaveChanges();

				TempData["mensaje"] = " El libro se actualizó correctamente";
				return RedirectToAction("Index");
			}
			return View();
		}
		#endregion

		#region Formulario para eliminar un libro
		public IActionResult Delete(int? id)
		{
			if (id == null || id.Equals(0))
			{
				return NotFound();
			}

			//Obtener libro 
			var libro = _context.Libro.Find(id);
			if (libro == null)
			{
				return NotFound();
			}
			return View(libro);
		}
		#endregion

		#region Metodo HttpPost para editar un libro
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult DeleteLibro(int? id)
		{
			if(id == null || id.Equals(0))
			{
				return NotFound();
			}
			//Obtener el libro
			var libro = _context.Libro.Find(id);
			if(libro == null)
			{
				return NotFound();
			}
				_context.Libro.Remove(libro);
				_context.SaveChanges();

				TempData["mensaje"] = " El libro se ha eliminado correctamente";
				return RedirectToAction("Index");
		}
		#endregion

	}
}

MyCRUD/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MyCRUD/Views/Libros/Create.cshtml
@model MyCRUD.Models.Libro
@{
	ViewData["Title"] = "Create";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
	<div class="py-5 text-center">
		<h2>Agregar un nuevo libro</h2>
		<span class="lead">formulario para agregar un nuevo libro a la base de datos del sistema</span>
  </div>

	<!-- Formulario -->
	<div class="row">
		<div class="col-8 mx-auto">
			<div class="card">
				<div class="card-body">
					<form method="post" asp-action="Create">
						<div asp-validation-summary="ModelOnly" class="text-danger"></div>
						<div class="form-group">
							<label class="control-label" asp-for="Titulo"></label>
							<input asp-for="Titulo" class="form-control" />
							<span asp-validation-for="Titulo" class="text-danger"></span>
						</div>
						<div class="form-group">
							<label class="control-label" asp-for="Descripcion"></label>
							<input asp-for="Descripcion" class="form-control" />
							<span asp-validation-for="Descripcion" class="text-danger"></span>
						</div>
						<div class="form-group">
							<label class="control-label" asp-for="FechaLanzamiento"></label>
							<input asp-for="FechaLanzamiento" class="form-control" />
							<span asp-validation-for="FechaLanzamiento" class="text-danger"></span>
						</div>
						<div class="form-group">
							<label class="control-label" asp-for="Autor"></label>
							<input asp-for="Autor" class="form-control" />
							<span asp-validation-for="Autor" class="text-danger"></span>
						</div>
						<div class="form-group">
							<label class="control-label" asp-for="Precio"></label>
							<input asp-for="Precio" class="form-control" />
							<span asp-validation-for="Precio" class="text-danger"></span>
						</div>
						<div class="form-group d-flex justify-content-end">
							<input type="submit" value="Crear Libro" class="btn btn-primary mx-2" />
							<input type="reset" value="Cancelar" class="btn btn-danger mx-2" />
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

@section Scripts{
	@{ <partial name="_ValidationScriptsPartial" />}
} 

MyCRUD/Views/Libros/Delete.cshtml
@model MyCRUD.Models.Libro
@{
	ViewData["Title"] = "Create";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
	<div class="py-5 text-center">
		<h2>Eliminar  libro</h2>
		<span class="lead">formulario para eliminar un libro</span>
  </div>

	<!-- Formulario -->
	<div class="row">
		<div class="col-8 mx-auto">
			<div class="card">
				<div class="card-body">
					<form method="post" asp-action="DeleteLibro">
						<div asp-validation-summary="ModelOnly" class="text-danger"></div>
						<input type="hidden" asp-for="Id" />
						<div class="form-group">
							<label class="control-label" asp-for="Titulo"></label>
							<input asp-for="Titulo" class="form-control" readonly />
							<span asp-validation-for="Titulo" class="text-danger"></span>
						</div>
						<div class="form-group">
							<label class="control-label" asp-for="Descripcion"></label>
							<input asp-for="Descripcion" class="form-control" readonly />
							<span asp-validation-for="Descripcion" class="text-danger"></span>
						</div>
						<div class="form-group">
							<label class="control-label" asp-for="FechaLanzamiento"></label>
							<input asp-for="FechaLanzamiento" class="form-control" readonly />
							<span asp-validation-for="FechaLanzamiento" class="text-danger"></span>
						</div>
						<div class="form-group">
							<label class="control-label" asp-for="Autor"></label>
							<input asp-for="Autor" class="form-control" readonly/>
							<span asp-validation-for="Autor" class="text-danger"></span>
						</div>
						<div class="form-group">
							<label class="control-label" asp-for="Precio"></label>
							<input asp-for="Precio" class="form-control" readonly/>
							<span asp-validation-for="Precio" class="text-danger"></span>
						</div>
						<div class="form-group d-flex justify-content-end">
							<input type="submit" value="Eliminar Libro" class="btn btn-primary mx-2" />
							<input type="reset" value="Cancelar" class="btn btn-danger mx-2" />
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

@section Scripts{
	@{ <partial name="_ValidationScriptsPartial" />}
} 

MyCRUD/Views/Libros/Edit.cshtml
@model MyCRUD.Models.Libro
@{
	ViewData["Title"] = "Create";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
	<div class="py-5 text-center">
		<h2>Editar  libro</h2>
		<span class="lead">formulario para editarr un libro</span>
  </div>

	<!-- Formulario -->
	<div class="row">
		<div class="col-8 mx-auto">
			<div class="card">
				<div class="card-body">
					<form method="post" asp-action="Edit">
						<div asp-validation-summary="ModelOnly" class="text-danger"></div>
						<input type="hidden" asp-for="Id" />
						<div class="form-group">
							<label class="control-label" asp-for="Titulo"></label>
							<input asp-for="Titulo" class="form-control" />
							<span asp-validation-for="Titulo" class="text-danger"></span>
						</div>
						<div class="form-group">
							<label class="control-label" asp-for="Descripcion"></label>
							<input asp-for="Descripcion" class="form-control" />
							<span asp-validation-for="Descripcion" class="text-danger"></span>
						</div>
						<div class="form-group">
							<label class="control-label" asp-for="FechaLanzamiento"></label>
							<input asp-for="FechaLanzamiento" class="form-control" />
							<span asp-validation-for="FechaLanzamiento" class="text-danger"></span>
						</div>
						<div class="form-group">
							<label class="control-label" asp-for="Autor"></label>
							<input asp-for="Autor" class="form-control" />
							<span asp-validation-for="Autor" class="text-danger"></span>
						</div>
						<div class="form-group">
							<label class="control-label" asp-for="Precio"></label>
							<input asp-for="Precio" class="form-control" />
							<span asp-validation-for="Precio" class="text-danger"></span>
						</div>
						<div class="form-group d-flex justify-content-end">
							<input type="submit" value="Editar Libro" class="btn btn-primary mx-2" />
							<input type="reset" value="Cancelar" class="btn btn-danger mx-2" />
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

@section Scripts{
	@{ <partial name="_ValidationScriptsPartial" />}
} 

MyCRUD/Views/Libros/Index.cshtml
@model IEnumerable<MyCRUD.Models.Libro>

@{
	ViewData["Title"] = "Lista de libros";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
	@if (TempData["mensaje"] != null){
				<div class="alert alert-success alert-dismissible fade show" role="alert">
					<strong><i class="fas fa-thumbs-up"></i> Bién!</strong>
					<p>@TempData["mensaje"]</p>
					<button class="close" data-dismiss="alert" aria-label="close" type="button">
						<i class="fas fa-times" aria-hidden="true"></i>
					</button>
				</div>
			}
	<div class="row my-4">
		<div class="col-sm-8">
			<h3><i class="fas fa-book"></i>&nbsp;Lista de Libros</h3>
		</div>
		<div class="col-sm-4">
			<a class="btn btn-success d-block" asp-action="Create" asp-controller="Libros"><i class="fas fa-plus-circle"></i>&nbsp;Nuevo Libro</a>
		</div>
	</div>
	<div class="row">
		@if (Model.Count() > 0)
		{
			<div class="col-12">
				<div class="table-responsive">
					<table class="table table-bordered table-striped table-sm">
						<thead>
							<tr>
								<th>@Html.DisplayNameFor(m => m.Id)</th>
								<th>@Html.DisplayNameFor(m => m.Titulo)</th>
								<th>@Html.DisplayNameFor(m => m.Descripcion)</th>
								<th>@Html.DisplayNameFor(m => m.FechaLanzamiento)</th>
								<th>@Html.DisplayNameFor(m => m.Autor)</th>
								<th>@Html.DisplayNameFor(m => m.Precio)</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							@foreach (var item in Model)
							 {
									<tr>
										<td>@item.Id</td>
										<td>@item.Titulo</td>
										<td>@item.Descripcion</td>
										<td>@item.FechaLanzamiento</td>
										<td>@item.Autor</td>
										<td>@item.Precio</td>
										<td>
											<a asp-controller="Libros" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info btn-sm">
											<i class="fas fa-pen-alt"></i>
											</a>
											<a asp-controller="Libros" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">
											<i class="fas fa-trash"></i>
											</a>
										</td>
									</tr>
							 }
						</tbody>
					</table>
				</div>
			</div>
		}else
		{
	<div class="col-12">
		<div class="alert alert-danger">No existen registros</div>
	</div>
		}
	</div>
</div>

MyCRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyCRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyCRUD</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
									<ul class="navbar-nav flex-grow-1">
										<li class="nav-item">
											<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
										</li>
										<li class="nav-item">
											<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
										</li>
										<li class="nav-item">
											<a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="Index">Libros</a>
										</li>
									</ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MyCRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/fontawesome/js/all.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>